/***********************************************************************
 ** Author:	jaron.ho
 ** Date:	2015-08-10
 ** Brief:	resource config
 ***********************************************************************/
var DEFAULT_DIR = "res/atlas/";	                    // 图集目录
var AUDIO_DIR = "res/Audio/";	                    // 音频目录
var EFFECT_DIR = "res/Effect/";	                    // 特效目录
var FONT_DIR = "res/Font/";	                        // 字体目录
var PICTURE_DIR = "res/Picture/";	                // 图片目录
var ROLE_DIR = "res/Role/";		                    // 角色目录
//----------------------------------------------------------------------
// 资源路径配置,标签:自定义
var ResourceConfig = {
    //----------------------------------------------------------------------
    // 图集
    atlas: [
        {url:DEFAULT_DIR + "comp.json", type:laya.net.Loader.ATLAS}
    ],
	//----------------------------------------------------------------------
    // 音频
    audio: [
		{url:AUDIO_DIR + "bgm_cardbing.mp3", type:laya.net.Loader.SOUND},
		{url:AUDIO_DIR + "button_click.mp3", type:laya.net.Loader.SOUND}
    ],
	//----------------------------------------------------------------------
    // 特效
    effect: [
		{url:EFFECT_DIR + "faguang.png", type:laya.net.Loader.IMAGE},
        {url:EFFECT_DIR + "faguang.sk", type:laya.net.Loader.BUFFER},
		{url:EFFECT_DIR + "faka.png", type:laya.net.Loader.IMAGE},
        {url:EFFECT_DIR + "faka.sk", type:laya.net.Loader.BUFFER}
    ],
	//----------------------------------------------------------------------
    // 字体
    font: [
        {url:FONT_DIR + "cardbing_number_award.fnt", spacing:-4},
		{url:FONT_DIR + "cardbing_number_black.fnt", spacing:2},
        {url:FONT_DIR + "cardbing_number_white.fnt", spacing:1}
    ],
    //----------------------------------------------------------------------
    // 图片
    picture: [
		{url:PICTURE_DIR + "black_grid_light.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "black_grid1.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "black_grid2.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "black_grid3.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "black_grid4.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "black_grid5.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "black_grid6.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "btn_bet_colour_blue.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "btn_bet_colour_green.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "btn_bet_colour_orange.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "btn_bet_colour_purple.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "btn_bet_colour_red.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "btn_bet_colour_yellow.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "btn_bet_count_big.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "btn_bet_count_small.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "btn_bet_number_even.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "btn_bet_number_odd.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cardbing_btn_bet_bgm_0.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cardbing_btn_bet_bgm_1.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cardbing_btn_bet_close.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cardbing_btn_bet_sound_0.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cardbing_btn_bet_sound_1.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_back_01.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cardbing_img_back_02.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_ball_1.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_ball_2.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_ball_3.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_ball_4.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_ball_5.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_ball_6.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_bet_award_complet.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cardbing_img_bet_set.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_bg.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_cad_1.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_cad_2.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_cad_3.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_cad_4.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_cad_5.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_img_cad_6.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_word_sd.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_word_sjwcjl.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "cardbing_word_yy.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_back.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_btn_cancel_01.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_btn_select_big_01.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_btn_select_big_02.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_btn_select_small_01.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_btn_select_small_02.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_btn_set_01.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_in_all.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_in_mine.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_state_select_0.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_state_select_1.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_word_sd.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_word_start.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "cbnet_bet_word_timedown.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "fk_guang.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "image_bg_gray.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "image_progress_bar.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "image_progress_bg.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "image_progress_mask.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "image_res_loading_bg.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "lottery_back_00.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "lottery_back_01.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "lottery_back_02.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "lottery_back_03.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "lottery_word_js.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "lottery_word_os.png", type:laya.net.Loader.IMAGE},
		{url:PICTURE_DIR + "lottery_word_qs.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_blue_0.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_blue_1.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_blue_2.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_blue_3.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_blue_4.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_blue_5.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_blue_6.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_blue_7.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_blue_8.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_blue_9.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_green_0.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_green_1.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_green_2.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_green_3.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_green_4.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_green_5.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_green_6.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_green_7.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_green_8.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_bet_green_9.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_cd_0.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_cd_1.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_cd_2.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_cd_3.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_cd_4.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_cd_5.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_cd_6.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_cd_7.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_cd_8.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_cd_9.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_..png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_-.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_0.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_1.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_2.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_3.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_4.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_5.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_6.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_7.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_8.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_9.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_bei.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_x.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_..png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_-.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_0.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_1.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_2.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_3.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_4.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_5.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_6.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_7.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_8.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_9.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_bei.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_black_x.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_..png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_-.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_0.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_1.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_2.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_3.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_4.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_5.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_6.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_7.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_8.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_9.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_bei.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_blue_x.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_none_0.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_none_1.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_none_2.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_none_3.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_none_4.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_none_5.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_none_6.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_none_7.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_none_8.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_none_9.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_..png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_-.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_0.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_1.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_2.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_3.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_4.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_5.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_6.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_7.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_8.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_9.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_bei.png", type:laya.net.Loader.IMAGE},
        {url:PICTURE_DIR + "number_normal_red_x.png", type:laya.net.Loader.IMAGE}
    ],
	//----------------------------------------------------------------------
    // 角色
    role: [
    ]
};